server:
  port: 4000

# postgre -> create database ts-dev
db:
  type: "postgres"
  port: 5432
  database: "ts-dev"

jwt:
  expiresIn: 3600

jwt-refresh:
  exp: 200000

cache:
    exp: 0

  exp: 0

game:
  rating-variable: 32
  expected-win-rate-point: 400
